# Generated by Django 3.1.7 on 2021-03-20 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_owner', to='passcode.code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
